### ISSUE TITLE
why?

### ISSUE THREAD

**Issue by shuangmei** [komrad36/RGB2Y#1]
D:\fubao\VCProject\RGB2Y\Debug>RGB2Y.exe

------------- RGB2Y ------------
Warming up...
Testing...
------------ OpenCV ------------
Warming up...
Testing...
0 pixels disagree.
RGB2Y      took 15139.5 us.
OpenCV     took 2592.71 us.

This is my test result.
OPENCV 3.4.3  version

**Comment by komrad36** [comment]
Just pushed some performance improvements and bug fixes, please try now. Also please make sure you're using a nontrivial image (i.e. at least 128 or so rows and cols). Finally please make sure you have enabled RGB2Y's multithreading and AVX2 support. (i.e. the new default options should be good).

-Kareem
